[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
checking_instruction_accounts = "ECPNcVp1HfG9x8HagrLX9yWVvDTBVdXb14jSVXURXuii"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
